name: Codecov

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

concurrency:
  group: codecov
  cancel-in-progress: false

jobs:
  codecov:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4
            
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
