# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Test Intensive

on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

  schedule:
    - cron: '0 * */1 * *'

  workflow_dispatch:

concurrency:
  group: go_test
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19.4
        check-latest: true
        cache-dependency-path: go.sum
        cache: true
        go-version-file: go.mod

    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v ./...



  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3

      - name: Test Short
        run: go test -v -run="^Test" -short ./... -timeout 20m

  test-intensive:
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: go test -v -run="^Test" ./... -timeout 6h




